import type { GameRules } from "@/types/game";
import type { Player } from "@/types/player";
import { createDefaultDefensiveProfile } from "./defenseEngine.ts";
import { createZeroStats } from "./statCalculations.ts";

export const testTeamName = "Mavericks";

export const defaultGameRules: GameRules = {
  homeRunLimitEnabled: true,
  homeRunLimit: 3,
  afterHomeRunLimit: "Single",
  runLimitPerInning: 5,
  mercyRule: "15 after 4 innings",
  courtesyRunnersAllowed: true,
  walksAllowed: true,
  sacFliesTracked: true,
  errorsTracked: true,
  fieldersChoicesTracked: true,
};

export const seedPlayers: Player[] = [
  {
    id: "maya-johnson",
    name: "Maya Johnson",
    gender: "Female",
    bats: "Left",
    throws: "Right",
    primaryPosition: "LC",
    speedRating: "Fast",
    notes: "Line-drive contact hitter, rarely pops up, good first-game leadoff profile.",
    contactNotes: ["Hits line drives", "Can place the ball", "Fast runner"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "High OBP table-setter",
    isActive: true,
    seedOrder: 1,
    seasonStats: createZeroStats(),
  },
  {
    id: "jordan-lee",
    name: "Jordan Lee",
    gender: "Male",
    bats: "Right",
    throws: "Right",
    primaryPosition: "SS",
    speedRating: "Average",
    notes: "Best all-around bat in the seed profile with gap power.",
    contactNotes: ["Usually hits gaps", "Good with runners on"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Best overall hitter",
    isActive: true,
    seedOrder: 2,
    seasonStats: createZeroStats(),
  },
  {
    id: "alex-smith",
    name: "Alex Smith",
    gender: "Male",
    bats: "Right",
    throws: "Right",
    primaryPosition: "3B",
    speedRating: "Average",
    notes: "Strong contact bat who fits an RBI slot.",
    contactNotes: ["Hits hard ground balls", "Good with runners on"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Strong contact + RBI hitter",
    isActive: true,
    seedOrder: 3,
    seasonStats: createZeroStats(),
  },
  {
    id: "sam-green",
    name: "Sam Green",
    gender: "Male",
    bats: "Left",
    throws: "Left",
    primaryPosition: "1B",
    speedRating: "Slow",
    notes: "Power profile with the best damage upside.",
    contactNotes: ["Usually hits gaps", "Power hitter", "Slow runner"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Best power hitter",
    isActive: true,
    seedOrder: 4,
    seasonStats: createZeroStats(),
  },
  {
    id: "riley-park",
    name: "Riley Park",
    gender: "Female",
    bats: "Switch",
    throws: "Right",
    primaryPosition: "LF",
    speedRating: "Average",
    notes: "Extra-base hit threat behind the cleanup slot.",
    contactNotes: ["Pulls everything", "Usually hits gaps"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Next-best power hitter",
    isActive: true,
    seedOrder: 5,
    seasonStats: createZeroStats(),
  },
  {
    id: "casey-kim",
    name: "Casey Kim",
    gender: "Female",
    bats: "Right",
    throws: "Right",
    primaryPosition: "2B",
    speedRating: "Average",
    notes: "Solid remaining hitter with steady contact.",
    contactNotes: ["Can hit opposite field", "Contact hitter"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Best remaining hitter",
    isActive: true,
    seedOrder: 6,
    seasonStats: createZeroStats(),
  },
  {
    id: "drew-allen",
    name: "Drew Allen",
    gender: "Male",
    bats: "Right",
    throws: "Right",
    primaryPosition: "RF",
    speedRating: "Slow",
    notes: "Power is useful, but contact can be streaky.",
    contactNotes: ["Inconsistent but has power", "Pops up too much"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Useful but flawed hitter",
    isActive: true,
    seedOrder: 7,
    seasonStats: createZeroStats(),
  },
  {
    id: "ari-stone",
    name: "Ari Stone",
    gender: "Female",
    bats: "Unknown",
    throws: "Right",
    primaryPosition: "C",
    speedRating: "Slow",
    notes: "Lower-order profile until first-game stats say otherwise.",
    contactNotes: ["Weak grounders", "Bottom-order hitter"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Weakest hitter hidden",
    isActive: true,
    seedOrder: 8,
    seasonStats: createZeroStats(),
  },
  {
    id: "taylor-fox",
    name: "Taylor Fox",
    gender: "Female",
    bats: "Left",
    throws: "Right",
    primaryPosition: "RC",
    speedRating: "Fast",
    notes: "Contact hitter who helps turn the lineup over.",
    contactNotes: ["Can place the ball", "Good runner"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Contact hitter",
    isActive: true,
    seedOrder: 9,
    seasonStats: createZeroStats(),
  },
  {
    id: "noa-cohen",
    name: "Noa Cohen",
    gender: "Female",
    bats: "Switch",
    throws: "Right",
    primaryPosition: "CF",
    speedRating: "Fast",
    notes: "Second leadoff type with speed near the lineup turn.",
    contactNotes: ["Fast runner", "Good contact", "Second leadoff type"],
    defensiveProfile: createDefaultDefensiveProfile(),
    roleHint: "Second leadoff type",
    isActive: true,
    seedOrder: 10,
    seasonStats: createZeroStats(),
  },
];
