-- CreateEnum
CREATE TYPE "OutType" AS ENUM ('GROUNDOUT', 'FLYOUT', 'LINEOUT', 'STRIKEOUT_LOOKING', 'STRIKEOUT_SWINGING', 'OTHER_OUT');

-- AlterTable
ALTER TABLE "AtBat" ADD COLUMN "outType" "OutType";

-- AlterTable
ALTER TABLE "PlayerGameStats"
ADD COLUMN "groundouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "flyouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lineouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsLooking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsSwinging" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "otherOuts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "doublePlays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "productiveOuts" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PlayerSeasonStats"
ADD COLUMN "groundouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "flyouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lineouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsLooking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsSwinging" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "otherOuts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "doublePlays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "productiveOuts" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "TeamGameStats"
ADD COLUMN "groundouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "flyouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lineouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsLooking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsSwinging" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "otherOuts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "doublePlays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "productiveOuts" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "TeamSeasonStats"
ADD COLUMN "groundouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "flyouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lineouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsLooking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "strikeoutsSwinging" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "otherOuts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "doublePlays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "productiveOuts" INTEGER NOT NULL DEFAULT 0;
